### ISSUE TITLE
Import of sound-files from steam fails

### ISSUE THREAD

**Issue by M-arcus** [Kasu/darkestdungeon#73]
When executing the import skript (`node .\dev\importAssetsFromDD.js <my-steam-directory>`), I'm getting no error message, only 8 eight lines of exported files. 

Then I execute `npm run dev-server`, the script can't find any `wav`-files, and fails.

**Comment by Kasu** [comment]
Please attach the error the dev-server gives you when it cannot find the audio files.

**Comment by M-arcus** [comment]
Now it fails earlier than before:
```
$ node ./dev/importAssetsFromDD.js /home/user/.local/share/Steam
Importing /home/user/.local/share/Steam/steamapps/common/DarkestDungeon/audio/secondary_banks/ambience.bank
Importing /home/user/.local/share/Steam/steamapps/common/DarkestDungeon/audio/secondary_banks/town.bank
Importing /home/user/.local/share/Steam/steamapps/common/DarkestDungeon/audio/secondary_banks/ui_shared.bank
Importing /home/user/.local/share/Steam/steamapps/common/DarkestDungeon/audio/secondary_banks/ui_town.bank
Importing /home/user/.local/share/Steam/steamapps/common/DarkestDungeon/audio/secondary_banks/music.bank
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1021:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:494:9)
    at Object.fsb.extract (/var/www/darkestdungeon/node_modules/darkest_dungeon_tools/lib/extract_fsb.js:33:18)
    at split_fsb.async (/var/www/darkestdungeon/dev/importAssetsFromDD.js:72:46)
    at /var/www/darkestdungeon/node_modules/darkest_dungeon_tools/lib/split_fsb.js:45:13
    at FSReqWrap.oncomplete (fs.js:136:15)
```

**Comment by Kasu** [comment]
it looks like you're running the command without access credentials on your system. The command needs to read and write files. Could you confirm if this is true?
